SELECT A.AUTHOR_ID AS AUTHOR_ID, 
C.AUTHOR_NAME AS AUTHOR_NAME, 
A.CATEGORY AS CATEGORY, 
SUM(B.SALES*A.PRICE) AS TOTAL_SALES
FROM BOOK AS A JOIN BOOK_SALES AS B ON A.BOOK_ID = B.BOOK_ID JOIN AUTHOR AS C ON A.AUTHOR_ID = C.AUTHOR_ID
WHERE B.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC