WITH TMP AS(
SELECT WRITER_ID
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID)>=3)

SELECT USER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2),	
CONCAT(LEFT(TLNO,3),'-',SUBSTRING(TLNO,4,4),'-',RIGHT(TLNO,4))
FROM TMP B JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
ORDER BY USER_ID DESC




# WITH TEMP AS (
#     SELECT WRITER_ID
#     FROM USED_GOODS_BOARD 
#     GROUP BY WRITER_ID
#     HAVING COUNT(WRITER_ID) >= 3
# )

# SELECT USER_ID,NICKNAME,CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2),CONCAT(LEFT(TLNO,3),'-',SUBSTRING(TLNO,4,4),'-',RIGHT(TLNO,4))
# FROM USED_GOODS_USER U
# INNER JOIN TEMP T ON U.USER_ID = T.WRITER_ID
# ORDER BY USER_ID DESC
