SELECT INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS INFO RIGHT JOIN REST_REVIEW AS RE ON INFO.REST_ID = RE.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY INFO.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC


# SELECT A.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) SCORE 
# FROM REST_INFO A RIGHT JOIN REST_REVIEW B
# ON A.REST_ID = B.REST_ID
# WHERE ADDRESS LIKE '서울%'
# GROUP BY A.REST_ID
# ORDER BY SCORE DESC, FAVORITES DESC