WITH VALUE AS (
    SELECT A.DAILY_FEE, A.CAR_TYPE, B.HISTORY_ID,
    DATEDIFF(END_DATE, START_DATE)+1 AS PERIOD,
    CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN '90일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE)+1 >=30 THEN '30일 이상'
    WHEN DATEDIFF(END_DATE, START_DATE)+1 >=7 THEN '7일 이상'
    ELSE 'NONE' END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON 
    A.CAR_ID = B.CAR_ID
    WHERE A.CAR_TYPE = '트럭'
)

SELECT V.HISTORY_ID, ROUND(V.DAILY_FEE*V.PERIOD*(100-IFNULL(B.DISCOUNT_RATE,0))/100)AS FEE
FROM VALUE V LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON V.DURATION_TYPE = B.DURATION_TYPE AND V.CAR_TYPE = B.CAR_TYPE
ORDER BY 2 DESC, 1 DESC
