WITH JULY_TABLE AS (
    SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER)AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)
    
SELECT A.FLAVOR
FROM FIRST_HALF A JOIN JULY_TABLE B ON A.SHIPMENT_ID = B.SHIPMENT_ID
GROUP BY A.SHIPMENT_ID
ORDER BY SUM(A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
LIMIT 3;