# SELECT CONCAT('/home/grep/src/',B.FILE_ID,B.FILE_NAME,B.FILE_EXT )AS FILE_PATH
# FROM USED_GOODS_BOARD A LEFT JOIN USED_GOODS_FILE B ON A.BOARD_ID = B.BOARD_ID
# WHERE VIEWS = (
# SELECT MAX(VIEWS) 
# FROM USED_GOODS_BOARD
# ORDER BY FILE_ID DESC
# )
SELECT CONCAT("/home/grep/src/", B.BOARD_ID, "/",F.FILE_ID, F.FILE_NAME,F.FILE_EXT) FILE_PATH
FROM USED_GOODS_BOARD B JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC